version: '3'
services:
  pocrediscachettl:
    image: pocrediscachettl
    restart: on-failure
    ports:
      - "8090:8090"
      - "5005:5005"
    links:
      - redis

  redis:
    image: redis
    hostname: redis
    restart: on-failure
    expose:
      - "6379"
